#!/usr/bin/env node

var program = require("commander"),
	fs = require("fs"),
	path = require("path"),
	config = require("./config");

program
	.version("0.0.1")
	.option("-r, --root [path_to_be_served]", "root directory to be served", path.normalize)
	.parse(process.argv);

if (program.root === true)
    if (typeof config.get("root_dir") !== "undefined")
	   console.log(config.get("root_dir"));
	
if (typeof program.root === "string") {
	config.set("root_dir", program.root);
	config.save();
}
